### PR TITLE
Added an option to disable the loading of the help plugin.

### PR DESCRIPTION
**Pull request by afourney**
### Proposed change
Presently `aprsd server` always loads the help plugin. As long as the help plugin is loaded, it will always fire as soon as input starts with the letter `h`. Sometimes this in undesired. This PR allows the plugin to be disabled from the conf file (though it is of course enabled by default)

### Background: 
I am developing a ChatGPT-like assistant that operates on APRS ([aprs-assistant](https://github.com/afourney/aprs-assistant)), and I'd like to host it as an APRSd plugin. Importantly, because it is a chatbot, it should accept input regardless of how it is formatted.  I've written a plugin with a wildcard regex, and it mostly does want I want -- as long as help is disabled. With the help plugin enabled, the help response is retuned as soon as people say "Hi" or "Hello"!

### CODE REVIEW

**Review by hemna — CHANGES_REQUESTED** [review]
A few small tweaks her and looks good.

**Comment by hemna** [comment]
I think the plugin is responding because of the regex in the plugin looking for ^[hH]

https://github.com/craigerl/aprsd/blob/master/aprsd/plugin.py#L266

Might also be a good idea to change that regex to look specifically for 'help'

**Comment by hemna** [comment]
@afourney any updates?

**Comment by afourney** [comment]
> @afourney any updates?

Woops. I missed these notifications. I'll dig in to this in few hours and we can wrap this up.

**Comment by hemna** [comment]
ok great!  thanks, I'd like to get your PR in :)

**Comment by afourney** [comment]
Ok, I think the PR is much simpler now. Requested changes made.

**Comment by afourney** [comment]
@hemna I think everything should be in order?

**Review by hemna — APPROVED** [review]

**Pull request merged**
